#!/bin/sh -el

user=ubuntu
group=${user}

juju-log "installing nginx and pip"
apt-get install nginx python-pip -y

juju-log "creating application dirs and log files"

# Cleanup /etc/nginx/conf.d/*.conf
rm -rf /etc/nginx/conf.d/*.conf

# Touch a example file for locations
touch /etc/nginx/conf.d/locations.conf

# nginx conf
mkdir -p /home/application/static

# creating the apprc file
touch /home/application/apprc

juju-log "installing gunicorn"
pip install gunicorn

nginx_conf="${CHARM_DIR}/utils/nginx.conf"

juju-log "copying nginx config files"
[ -f /etc/nginx/nginx.conf ] && rm -f /etc/nginx/nginx.conf
ln -s ${nginx_conf} /etc/nginx/nginx.conf

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ${user}:${group} /var/lib/tsuru/
sudo chown -R ${user}:${group} /home/application/
