#!/bin/sh

CHARM_DIR=/var/lib/tsuru
APP_DIR=/home/application

# remove locations.conf file if exist
[ -f /etc/nginx/conf.d/locations.conf ] && \
    sudo rm -rf /etc/nginx/conf.d/locations.conf

# Copy locations.conf file from git to conf.d if exist
[ -f ${APP_DIR}/current/locations.conf ] && \
    sudo cp ${APP_DIR}/current/locations.conf /etc/nginx/conf.d

if [ -f ${APP_DIR}/gunicorn.pid ]
then
    pid=`cat ${APP_DIR}/gunicorn.pid`
    $CHARM_DIR/hooks/stop-gunicorn
    while [ -d /proc/${pid} ]
    do
        sleep 1
    done
fi

$CHARM_DIR/hooks/start-gunicorn
sudo service nginx reload
