#!/bin/sh -el

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

if [ -f ${CURRENT_DIR}/requirements.apt ]; then
    sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y
fi

if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    sudo -E pip install -U -r ${CURRENT_DIR}/requirements.txt
fi
