#!/bin/sh -el

user=ubuntu
group=${user}

juju-log "installing nginx and pip"
apt-get install nginx python-pip git ruby rubygems python-dev -y
gem install foreman -q --no-rdoc --no-ri

juju-log "installing circus"
pip install git+https://github.com/mozilla-services/circus.git

juju-log "installing tsuru-circus"
pip install tsuru-circus

# creating the apprc file
mkdir -p /home/application
touch /home/application/apprc
touch /home/application/foreman.log

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ${user}:${group} /var/lib/tsuru/
sudo chown -R ${user}:${group} /home/application/
