#!/bin/bash -el

user=ubuntu
group=${user}

juju-log "adding ppas"
add-apt-repository ppa:roman-imankulov/circus -y
apt-get update

juju-log "installing nginx, pip, python-dev and circus"
apt-get install nginx python-pip git python-dev circus -y

juju-log "installing tsuru-circus"
pip install tsuru-circus

# creating the apprc file
mkdir -p /home/application
touch /home/application/apprc

repository=`config-get app-repo`

if [ "$repository" ]
then
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ${user}:${group} /var/lib/tsuru/
sudo chown -R ${user}:${group} /home/application/

juju-log "removing the default nginx conf"
sudo rm /etc/nginx/sites-enabled/default

juju-log "configuring nginx"
nginx_conf="${CHARM_DIR}/utils/nginx.conf"

ln -s ${nginx_conf} /etc/nginx/sites-enabled/app.conf

juju-log "starting nginx"
service nginx start

juju-log "configuring circus"
circus_conf=/var/lib/tsuru/utils/circus.ini
cp ${circus_conf} /etc/circus/circus.ini

juju-log "starting circus"
start circus
