#!/bin/bash -el

user=ubuntu
group=${user}

echo "installing nginx, pip, python-dev"
apt-get install nginx python-pip git python-dev libzmq-dev g++ -y

echo "installing circus"
pip install git+http://github.com/mozilla-services/circus.git

echo "installing tsuru-circus"
pip install tsuru-circus

# creating the apprc file
mkdir -p /home/application
touch /home/application/apprc

CHARM_DIR=/var/lib/tsuru

sudo chown -R ${user}:${group} /var/lib/tsuru/
sudo chown -R ${user}:${group} /home/application/

echo "removing the default nginx conf"
[ -f /etc/nginx/sites-enabled/default ] && sudo rm /etc/nginx/sites-enabled/default

echo "configuring nginx"
nginx_conf="${CHARM_DIR}/utils/nginx.conf"

[ -f /etc/nginx/sites-enabled/app.conf ] || ln -s ${nginx_conf} /etc/nginx/sites-enabled/app.conf

echo "configuring circus"
circus_ini=/var/lib/tsuru/utils/circus.ini
mkdir -p /etc/circus
cp ${circus_ini} /etc/circus/circus.ini

echo "coping circus.conf to /etc/init"
circus_conf=/var/lib/tsuru/utils/circus.conf
cp ${circus_conf} /etc/init
