#!/bin/bash

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

if [ -d ${CURRENT_DIR} ]
then
    cd ${CURRENT_DIR}
    find . -name \*.pyc -delete
    find . -name \*.pyo -delete
fi

echo "Starting..."
circusctl --timeout 200 stop
circusctl --timeout 200 start
