#!/bin/bash

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

[ -f ${APP_DIR}/apprc ] && source ${APP_DIR}/apprc

if [ -d ${CURRENT_DIR} ]
then
    cd ${CURRENT_DIR}
    if [ -f Procfile ]
    then
        echo "Checking Procfile"
        foreman check
        circus_conf=/var/lib/tsuru/utils/circus.ini
        cp ${circus_conf} /home/application/circus.ini
        CMD=`cat Procfile|cut -d: -f2-`
        sed -i "s,CMD,${CMD},g" /home/application/circus.ini
        echo "Starting..."
        # sudo foreman export upstart -u ubuntu /etc/init
        circusd /home/application/circus.ini &
    else
        echo "Procfile not found!"
    fi
fi
