#!/bin/bash

set -eu

VIRTUALENV=/home/application/env

juju-log "installing nginx and virtualenv"
apt-get install -qqy nginx python-virtualenv

juju-log "creating application dirs and log files"
# nginx conf
mkdir -p /home/application/static

# creating the apprc file
touch /home/application/apprc

juju-log "creating the virtualenv and installing Django and gunicorn"
virtualenv --unzip-setuptools ${VIRTUALENV}
${VIRTUALENV}/bin/pip install django gunicorn

nginx_conf="${CHARM_DIR}/utils/nginx.conf"

juju-log "copying nginx config files"
ln -s ${nginx_conf} /etc/nginx/sites-enabled/application.conf
rm /etc/nginx/sites-enabled/default

juju-log "creating releases dir"
mkdir -p /home/application/releases

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ubuntu:ubuntu /var/lib/tsuru/
sudo chown -R ubuntu:ubuntu /home/application/
