#!/usr/bin/env bash

set -e

# set envinronment variables for the app
CHARM_DIR=/var/lib/tsuru
#source $CHARM_DIR/utils/environment.sh

APP_DIR=/home/application

NUM_WORKERS=3
VIRTUALENV=${APP_DIR}/env

pushd ${APP_DIR}/current
SETTINGS_FILE=$(find . -maxdepth 2 -type f -name 'settings.py' | head -1)
popd

PROJECT_DIR=$(dirname ${SETTINGS_FILE})
pushd $APP_DIR/current/${PROJECT_DIR}
${VIRTUALENV}/bin/gunicorn_django --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid
popd
