#!/bin/bash -el

APPLICATION=/home/application
CURRENT_DIR=${APPLICATION}/current

if [ -f ${CURRENT_DIR}/requirements.apt ]; then
    sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y
fi

GOPATH=${APPLICATION}/.go
PATH=${GOPATH}/bin:${PATH}
export GOPATH PATH

cd ${CURRENT_DIR} && go get ./...
