#!/bin/bash -el

APPLICATION=/home/application
CURRENT_DIR=${APPLICATION}/current

if [ -f ${CURRENT_DIR}/requirements.apt ]; then
	sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y
fi

GOROOT=${APPLICATION}/go
GOPATH=${APPLICATION}/.go
PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
export GOPATH GOROOT PATH

cd ${CURRENT_DIR} && go get -d ./...
