#!/bin/bash -lu

juju-log "installing mercurial, bzr and git"
apt-get install bzr mercurial git bzr -qqy

juju-log "creating application dirs and log files"
APPLICATION=/home/application
mkdir -p $APPLICATION
# creating the apprc file
touch $APPLICATION/apprc

juju-log "installing go"
ver=1.0.3
file=go$ver.linux-amd64.tar.gz
url=http://go.googlecode.com/files/$file

pushd $APPLICATION
	curl -sO $url
	tar zxf $file
	rm -f $file
popd

repository=`config-get app-repo`

if [ "$repository" ]
then
	version=`config-get app-version`
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Running git checkout $version on repository path"
	git --work-tree=/home/application/current --git-dir=/home/application/current/.git checkout $version
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ubuntu:ubuntu /var/lib/tsuru/
sudo chown -R ubuntu:ubuntu /home/application/
