#!/bin/bash -e

APPLICATION=/home/application
CURRENT_DIR=${APPLICATION}/current

GOPATH=${APPLICATION}/.go export GOPATH
PATH=${GOPATH}/bin:${PATH}
export PATH GOPATH

ENV_FILE=${APPLICATION}/apprc
[ -f ${ENV_FILE} ] && source ${ENV_FILE}

if [ -d ${CURRENT_DIR} ]; then
    pushd ${CURRENT_DIR}
        go build -o tsuru-app
	./tsuru-app &
    popd
fi
