#!/bin/bash -e

APPLICATION=/home/application
CURRENT_DIR=${APPLICATION}/current

GOROOT=${APPLICATION}/go
GOPATH=${APPLICATION}/.go
PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
export PATH GOPATH GOROOT

ENV_FILE=${APPLICATION}/apprc
[ -f ${ENV_FILE} ] && source ${ENV_FILE}

if [ -d ${CURRENT_DIR} ]; then
	cd ${CURRENT_DIR}
	go build -o tsuru-app
	./tsuru-app &
fi
