#!/bin/bash -el

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

echo "running requirements.yum"
if [ -f ${CURRENT_DIR}/requirements.yum ]; then
    sudo -E yum install $(cat ${CURRENT_DIR}/requirements.yum) --assumeyes --enablerepo=epel
fi

echo "exporting variables"
GOROOT=$APPLICATION/go export GOROOT
GOPATH=$APPLICATION/.go export GOPATH
PATH=$GOROOT/bin:$PATH

echo "executing go get"
pushd $CURRENT_DIR && go get ./...
popd
