#!/bin/bash

APPLICATION=/home/application
CURRENT_DIR=${APPLICATION}/current

echo "exporting variables"
GOROOT=${APPLICATION}/go export GOROOT
GOPATH=${APPLICATION}/.go export GOPATH
PATH=${GOROOT}/bin:${PATH}

if [ -d ${CURRENT_DIR} ]; then
    cd ${CURRENT_DIR}
        BIN=$(basename `pwd`)
        go build
        ./${BIN} &
    cd -
fi
