#!/bin/bash -lue

juju-log "installing git, make and gcc"
apt-get install -qqy git make gcc libssl-dev

juju-log "installing ruby"
curl http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p0.tar.gz > /tmp/ruby-2.0.0-p0.tar.gz
pushd /tmp
tar xzvf ruby-2.0.0-p0.tar.gz
popd

pushd /tmp/ruby-2.0.0-p0
./configure && make && sudo make install
popd

juju-log "installing bundler"
gem install bundler

juju-log "installing python dependencies for circus"
apt-get install -qqy python-dev libzmq-dev python-pip

juju-log "installing nginx"
apt-get install -qqy nginx

juju-log "installing circus"
pip install git+http://github.com/mozilla-services/circus.git

juju-log "installing tsuru-circus"
pip install tsuru-circus

juju-log "configuring circus"
mkdir -p /etc/circus
cp ${CHARM_DIR}/utils/circus.ini /etc/circus

juju-log "installing circus upstart job"
cp ${CHARM_DIR}/utils/circus.conf /etc/init

juju-log "creating application dirs and log files"
mkdir -p /home/application

# creating the apprc file
touch /home/application/apprc

repository=`config-get app-repo`

if [ "$repository" ]
then
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ubuntu:ubuntu /var/lib/tsuru
sudo chown -R ubuntu:ubuntu /home/application

juju-log "removing the default nginx conf"
sudo rm /etc/nginx/sites-enabled/default

juju-log "configuring nginx"
nginx_conf="${CHARM_DIR}/utils/nginx.conf"

ln -s ${nginx_conf} /etc/nginx/sites-enabled/app.conf
