#!/bin/bash -el

APP_DIR=/home/application
VIRTUALENV=${APP_DIR}/env
CURRENT_DIR=${APP_DIR}/current

if [ -f ${CURRENT_DIR}/requirements.apt ]; then
    sudo apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y
fi

if [ -f ${CURRENT_DIR}/Gemfile ]; then
 	$(cd ${CURRENT_DIR} ; bundle install)
fi
