#!/bin/bash -lu

juju-log "installing git"
apt-get install -qqy git

juju-log "installing make"
apt-get install -qqy make

juju-log "installing ruby"
apt-get install -qqy ruby1.9.3
sudo update-alternatives --set ruby `update-alternatives --list ruby | tail -1`
sudo update-alternatives --set gem `update-alternatives --list gem | tail -1`

juju-log "installing foreman"
gem install foreman -q --no-rdoc --no-ri

juju-log "installing bundler"
gem install bundler

juju-log "installing python dependencies for circus"
apt-get install -qqy python-dev libzmq-dev python-pip

juju-log "installing nginx"
apt-get install -qqy nginx

juju-log "installing circus"
pip install circus

juju-log "installing tsuru-circus"
pip install tsuru-circus

juju-log "creating application dirs and log files"
mkdir -p /home/application
# creating the apprc file
touch /home/application/apprc
touch /home/application/foreman.log

repository=`config-get app-repo`

if [ "$repository" ]
then
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ubuntu:ubuntu /var/lib/tsuru
sudo chown -R ubuntu:ubuntu /home/application

juju-log "removing the default nginx conf"
sudo rm /etc/nginx/sites-enabled/default

juju-log "configuring nginx"
nginx_conf="${CHARM_DIR}/utils/nginx.conf"

ln -s ${nginx_conf} /etc/nginx/sites-enabled/app.conf

juju-log "starting nginx"
service nginx start
