#!/bin/bash -lu

juju-log "installing git"
apt-get install -qqy git

juju-log "installing make"
apt-get install -qqy make

juju-log "installing ruby"
apt-get install -qqy ruby1.9.3
update-alternatives --set ruby `update-alternatives --list ruby | tail -1`
update-alternatives --set gem `update-alternatives --list gem | tail -1`

juju-log "installing bundler"
gem install bundler

juju-log "installing python dependencies for circus"
apt-get install -qqy python-dev libzmq-dev python-pip

juju-log "installing nginx"
apt-get install -qqy nginx

juju-log "installing circus"
pip install git+https://github.com/andrewsmedina/circus.git@validate_option_hooks

juju-log "installing tsuru-circus"
pip install tsuru-circus

juju-log "configuring circus"
mkdir -p /etc/circus
cp ${CHARM_DIR}/utils/circus.ini /etc/circus

juju-log "installing circus upstart job"
cp ${CHARM_DIR}/utils/circus.conf /etc/init

juju-log "creating application dirs and log files"
mkdir -p /home/application

# creating the apprc file
touch /home/application/apprc

hostname >> /etc/hosts

repository=`config-get app-repo`

if [ "$repository" ]
then
	version=`config-get app-version`
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Running git checkout $version on repository path"
	git --work-tree=/home/application/current --git-dir=/home/application/current/.git checkout $version || true
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

chown -R ubuntu:ubuntu /var/lib/tsuru
chown -R ubuntu:ubuntu /home/application

juju-log "removing the default nginx conf"
rm -f /etc/nginx/sites-enabled/default

juju-log "configuring nginx"
nginx_conf="${CHARM_DIR}/utils/nginx.conf"

ln -s ${nginx_conf} /etc/nginx/sites-enabled/app.conf

echo DEBIAN_FRONTEND=noninteractive >> /etc/profile
