#!/bin/bash -el

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

if [ -f ${CURRENT_DIR}/requirements.yum ]; then
    sudo -E yum install $(cat ${CURRENT_DIR}/requirements.yum) --assumeyes --enablerepo=epel
fi

if [ -f ${CURRENT_DIR}/Gemfile ]; then
    pushd $CURRENT_DIR && bundle install --deployment --without test development
    popd
fi
