#!/bin/bash

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

if [ -d $CURRENT_DIR ]; then
    cd $CURRENT_DIR
    if [ -f Procfile ]; then
        `cat Procfile |cut -d: -f2` >> $APP_DIR/ruby-server.log 2>&1 &
        echo $! > $APP_DIR/ruby-server.pid
    fi
    cd -
fi

