#!/usr/bin/env bash

set -eu

database=`relation-get database`

if [ -z "$database" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

juju-log "Adding database info on environment"

export DB_NAME=$database
export DB_USER=$user
export DB_PASSWORD=$password
export DB_HOST=$host
