#!/bin/sh -el

user=ubuntu
group=${user}

juju-log "installing nginx and git"
apt-get install nginx git -y

# removing the default docroot
mv /usr/share/nginx/www /usr/share/nginx/old

# creating the new docroot
ln -s /home/application/current /usr/share/nginx/www

# creating the apprc file
mkdir -p /home/application
touch /home/application/apprc

echo "127.0.0.1 `hostname`" >> /etc/hosts

repository=`config-get app-repo`

if [ "$repository" ]
then
	version=`config-get app-version`
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Running git checkout $version on repository path"
	git --work-tree=/home/application/current --git-dir=/home/application/current/.git checkout $version || true
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

chown -R ${user}:${group} /var/lib/tsuru/
chown -R ${user}:${group} /home/application/

echo DEBIAN_FRONTEND=noninteractive >> /etc/profile
