#!/bin/sh -el

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current

if [ -f ${CURRENT_DIR}/requirements.yum ]; then
    sudo yum install $(cat ${CURRENT_DIR}/requirements.yum) --assumeyes --enablerepo=epel
fi

if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    sudo pip-python install -r ${CURRENT_DIR}/requirements.txt
fi
