#!/bin/sh

CHARM_DIR=/var/lib/tsuru
APP_DIR=/home/application

$CHARM_DIR/hooks/stop-gunicorn

if [ -f ${APP_DIR}/gunicorn.pid ]; then
    while [ -d /proc/`cat ${APP_DIR}/gunicorn.pid` ]; do
        sleep 1
    done
fi

$CHARM_DIR/hooks/start-gunicorn
