#!/bin/sh

# set envinronment variables for the app
CHARM_DIR=/var/lib/tsuru
user=ubuntu

APP_DIR=/home/application

if [ -d ${APP_DIR}/current ]
then
    NUM_WORKERS=3
    VIRTUALENV=${APP_DIR}/env

    cd ${APP_DIR}/current
    SETTINGS_FILE=$(find . -maxdepth 2 -type f -name 'settings.py' | head -1)
    cd $OLDPWD

    ENV_FILE=${APP_DIR}/apprc
    [ -f ${ENV_FILE} ] && source ${ENV_FILE}
    PROJECT_DIR=$(dirname ${SETTINGS_FILE})
    cd $APP_DIR/current/${PROJECT_DIR}
    ${VIRTUALENV}/bin/gunicorn_django --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid
    cd $OLDPWD
else
    juju-log "skipping gunicorn start: app not deployed yet"
fi
