#!/usr/bin/env bash

set -e

# set envinronment variables for the app
CHARM_DIR=/var/lib/tsuru
user=stratus

APP_DIR=/home/application

NUM_WORKERS=3
VIRTUALENV=${APP_DIR}/env

pushd ${APP_DIR}/releases/current
SETTINGS_FILE=$(find . -maxdepth 2 -type f -name 'settings.py' | head -1)
popd

PROJECT_DIR=$(dirname ${SETTINGS_FILE})
pushd $APP_DIR/releases/current/${PROJECT_DIR}
sudo -u ${user} ${VIRTUALENV}/bin/gunicorn_django --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid
popd
