#!/bin/sh

# set envinronment variables for the app
CHARM_DIR=/var/lib/tsuru
APP_DIR=/home/application

if [ -d ${APP_DIR}/current ]
then
    NUM_WORKERS=3

    ENV_FILE=${APP_DIR}/apprc
    [ -f ${ENV_FILE} ] && source ${ENV_FILE}
    cd $APP_DIR/current/
    gunicorn --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid wsgi --access-logfile=${APP_DIR}/gunicorn_access.log --error-logfile=${APP_DIR}/gunicorn_error.log
    cd $OLDPWD
else
    juju-log "skipping gunicorn start: app not deployed yet"
fi
