#!/bin/bash -l

set -u

juju-log "installing make, g++ and git"
apt-get install -qqy make g++ git python-pip python-dev libzmq

juju-log "installing circus"
pip install git+git://github.com/mozilla-services/circus.git

juju-log "installing tsuru-circus"
pip install tsuru-circus

cd /tmp

juju-log "downloading node.js "
wget http://nodejs.org/dist/v0.8.20/node-v0.8.20.tar.gz 2>/dev/null

juju-log "uncompressing node.js"
tar xzf node-v0.8.20.tar.gz

juju-log "installing node.js"
cd node-v0.8.20
./configure && make && make install
cd -

juju-log "removing temporary files"
rm -rf /tmp/node-v0.8.20*

juju-log "creating application dirs and log files"
mkdir -p /home/application

# creating the apprc file
touch /home/application/apprc

repository=`config-get app-repo`

if [ "$repository" ]
then
	version=`config-get app-version`
	juju-log "Cloning $repository into /home/application/current"
	git clone --depth 1 $repository /home/application/current
	juju-log "Running git checkout $version on repository path"
	git --work-tree=/home/application/current --git-dir=/home/application/current/.git checkout $version
	juju-log "Installing dependencies..."
	${CHARM_DIR}/hooks/dependencies
fi

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ubuntu:ubuntu /var/lib/tsuru/
sudo chown -R ubuntu:ubuntu /home/application/
