#!/bin/bash

set -eu

juju-log "installing pip and nginx"
sudo apt-get install -qqy nginx gunicorn python-django

# copy charm folder in order to use nginx.conf
sudo mkdir /home/django-charm
sudo cp -r ../* /home/django-charm

juju-log "creating application dirs and log files"
# nginx conf
sudo mkdir /home/application
sudo mkdir /home/application/static
sudo touch /home/application/access.log
sudo touch /home/application/error.log
sudo chmod 765 /home/application/* -R

juju-log "copying nginx config files"
sudo ln -s /home/django-charm/utils/nginx.conf /etc/nginx/sites-available/application.conf
sudo ln -s /home/django-charm/utils/nginx.conf /etc/nginx/sites-enabled/application.conf

juju-log "restarting nginx"
sudo /etc/init.d/nginx stop
sudo /etc/init.d/nginx start
