#!/usr/bin/env bash

set -e

APP_DIR=/home/application
CHARM_DIR=/var/lib/tsuru

# set envinronment variables for the app
#source $CHARM_DIR/utils/environment.sh

source $CHARM_DIR/hooks/stop-gunicorn
source $CHARM_DIR/hooks/start-gunicorn
