#!/bin/sh -el

user=ubuntu
group=${user}

function lineNumber {
    grep "$2" -n "$1" | awk -F ':' '{print $1}'
}

juju-log "checking network"
while ! curl globo.com; do
       printf "."
       sleep 5
done

juju-log "installing nginx and pip"
yum install python-pip --enablerepo=epel --assumeyes

# creating the apprc file
touch /home/application/apprc

juju-log "linking the charm"
ln -s ${CHARM_DIR} /var/lib/tsuru

sudo chown -R ${user}:${group} /var/lib/tsuru/
sudo chown -R ${user}:${group} /home/application/
