#!/bin/sh

CHARM_DIR=/var/lib/tsuru
APP_DIR=/home/application

if [ -f ${APP_DIR}/gunicorn.pid ]
then
    pid=`cat ${APP_DIR}/gunicorn.pid`
    $CHARM_DIR/hooks/stop-gunicorn
    while [ -d /proc/${pid} ]
    do
        sleep 1
    done
fi

$CHARM_DIR/hooks/start-gunicorn
