options:
  app-repo:
    type: string
    default: ""
    description: "Git repository for the app."
  app-version:
    type: string
    default: "origin/master"
    description: "Git ref-id for the last code deployed in the app."
